import esbuild from "esbuild";
import fs from "node:fs/promises";
import path from "node:path";
import { builtinModules } from "node:module";

const ROOT = process.cwd();
const DIST_DIR = path.join(ROOT, "dist");
const MANIFEST_PATH = path.join(ROOT, "manifest.json");
const STYLES_PATH = path.join(ROOT, "styles.css");
const BUILD_TIMESTAMP_PATH = path.join(DIST_DIR, ".build-timestamp.txt");

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

async function copyIfExists(fromPath, toPath) {
	try {
		await fs.copyFile(fromPath, toPath);
		return true;
	} catch (error) {
		if (error && typeof error === "object" && "code" in error && error.code === "ENOENT") {
			return false;
		}
		throw error;
	}
}

function nowLabels() {
	const now = new Date();
	return {
		utc: now.toISOString(),
		utcPlus8: new Intl.DateTimeFormat("sv-SE", {
			timeZone: "Asia/Shanghai",
			dateStyle: "short",
			timeStyle: "medium",
		}).format(now),
	};
}

function formatTimestampLabels(labels) {
	return `UTC ${labels.utc} | UTC+8 ${labels.utcPlus8}`;
}

async function writeBuildTimestamp() {
	const labels = nowLabels();
	await fs.writeFile(BUILD_TIMESTAMP_PATH, `${labels.utc}\n`, "utf8");
	return labels;
}

async function syncReleaseAssets() {
	await fs.mkdir(DIST_DIR, { recursive: true });
	await fs.copyFile(MANIFEST_PATH, path.join(DIST_DIR, "manifest.json"));
	const hasStyles = await copyIfExists(STYLES_PATH, path.join(DIST_DIR, "styles.css"));
	const timestamps = await writeBuildTimestamp();
	console.log(`[${formatTimestampLabels(timestamps)}] Synced manifest.json${hasStyles ? " and styles.css" : ""} to dist`);
}

await syncReleaseAssets();

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: "inline",
	treeShaking: true,
	outfile: "dist/main.js",
	minify: false,
	plugins: [
		{
			name: "sync-release-assets",
			setup(build) {
				build.onEnd(async (result) => {
					if (result.errors.length > 0) {
						console.log(`[${formatTimestampLabels(nowLabels())}] Build failed. dist assets not updated.`);
						return;
					}
					await syncReleaseAssets();
					console.log(`[${formatTimestampLabels(nowLabels())}] Build finished.`);
				});
			},
		},
	],
});

await context.watch();
console.log("Watching src files. dist/main.js is updated on change.");
